import { JWTOptions } from "google-auth-library";
import * as grpc from "@grpc/grpc-js";
import { StatusObject } from "@grpc/grpc-js";
import { google } from "../definitions/googleads";
import { Status } from "@grpc/grpc-js/build/src/constants";
import { ServiceClient } from "@grpc/grpc-js/build/src/make-client";
import { Logger } from "winston";
import { Statter } from "./statter";
declare const services: {
    Operations: typeof google.longrunning.Operations;
    Operation: typeof google.longrunning.Operation;
    GetOperationRequest: typeof google.longrunning.GetOperationRequest;
    ListOperationsRequest: typeof google.longrunning.ListOperationsRequest;
    ListOperationsResponse: typeof google.longrunning.ListOperationsResponse;
    CancelOperationRequest: typeof google.longrunning.CancelOperationRequest;
    DeleteOperationRequest: typeof google.longrunning.DeleteOperationRequest;
    WaitOperationRequest: typeof google.longrunning.WaitOperationRequest;
    OperationInfo: typeof google.longrunning.OperationInfo;
    AccountBudgetProposalService: typeof google.ads.googleads.v14.services.AccountBudgetProposalService;
    MutateAccountBudgetProposalRequest: typeof google.ads.googleads.v14.services.MutateAccountBudgetProposalRequest;
    AccountBudgetProposalOperation: typeof google.ads.googleads.v14.services.AccountBudgetProposalOperation;
    MutateAccountBudgetProposalResponse: typeof google.ads.googleads.v14.services.MutateAccountBudgetProposalResponse;
    MutateAccountBudgetProposalResult: typeof google.ads.googleads.v14.services.MutateAccountBudgetProposalResult;
    AccountLinkService: typeof google.ads.googleads.v14.services.AccountLinkService;
    CreateAccountLinkRequest: typeof google.ads.googleads.v14.services.CreateAccountLinkRequest;
    CreateAccountLinkResponse: typeof google.ads.googleads.v14.services.CreateAccountLinkResponse;
    MutateAccountLinkRequest: typeof google.ads.googleads.v14.services.MutateAccountLinkRequest;
    AccountLinkOperation: typeof google.ads.googleads.v14.services.AccountLinkOperation;
    MutateAccountLinkResponse: typeof google.ads.googleads.v14.services.MutateAccountLinkResponse;
    MutateAccountLinkResult: typeof google.ads.googleads.v14.services.MutateAccountLinkResult;
    AdGroupAdLabelService: typeof google.ads.googleads.v14.services.AdGroupAdLabelService;
    MutateAdGroupAdLabelsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupAdLabelsRequest;
    AdGroupAdLabelOperation: typeof google.ads.googleads.v14.services.AdGroupAdLabelOperation;
    MutateAdGroupAdLabelsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupAdLabelsResponse;
    MutateAdGroupAdLabelResult: typeof google.ads.googleads.v14.services.MutateAdGroupAdLabelResult;
    AdGroupAdService: typeof google.ads.googleads.v14.services.AdGroupAdService;
    MutateAdGroupAdsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupAdsRequest;
    AdGroupAdOperation: typeof google.ads.googleads.v14.services.AdGroupAdOperation;
    MutateAdGroupAdsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupAdsResponse;
    MutateAdGroupAdResult: typeof google.ads.googleads.v14.services.MutateAdGroupAdResult;
    AdGroupAssetService: typeof google.ads.googleads.v14.services.AdGroupAssetService;
    MutateAdGroupAssetsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupAssetsRequest;
    AdGroupAssetOperation: typeof google.ads.googleads.v14.services.AdGroupAssetOperation;
    MutateAdGroupAssetsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupAssetsResponse;
    MutateAdGroupAssetResult: typeof google.ads.googleads.v14.services.MutateAdGroupAssetResult;
    AdGroupAssetSetService: typeof google.ads.googleads.v14.services.AdGroupAssetSetService;
    MutateAdGroupAssetSetsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupAssetSetsRequest;
    AdGroupAssetSetOperation: typeof google.ads.googleads.v14.services.AdGroupAssetSetOperation;
    MutateAdGroupAssetSetsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupAssetSetsResponse;
    MutateAdGroupAssetSetResult: typeof google.ads.googleads.v14.services.MutateAdGroupAssetSetResult;
    AdGroupBidModifierService: typeof google.ads.googleads.v14.services.AdGroupBidModifierService;
    MutateAdGroupBidModifiersRequest: typeof google.ads.googleads.v14.services.MutateAdGroupBidModifiersRequest;
    AdGroupBidModifierOperation: typeof google.ads.googleads.v14.services.AdGroupBidModifierOperation;
    MutateAdGroupBidModifiersResponse: typeof google.ads.googleads.v14.services.MutateAdGroupBidModifiersResponse;
    MutateAdGroupBidModifierResult: typeof google.ads.googleads.v14.services.MutateAdGroupBidModifierResult;
    AdGroupCriterionCustomizerService: typeof google.ads.googleads.v14.services.AdGroupCriterionCustomizerService;
    MutateAdGroupCriterionCustomizersRequest: typeof google.ads.googleads.v14.services.MutateAdGroupCriterionCustomizersRequest;
    AdGroupCriterionCustomizerOperation: typeof google.ads.googleads.v14.services.AdGroupCriterionCustomizerOperation;
    MutateAdGroupCriterionCustomizersResponse: typeof google.ads.googleads.v14.services.MutateAdGroupCriterionCustomizersResponse;
    MutateAdGroupCriterionCustomizerResult: typeof google.ads.googleads.v14.services.MutateAdGroupCriterionCustomizerResult;
    AdGroupCriterionLabelService: typeof google.ads.googleads.v14.services.AdGroupCriterionLabelService;
    MutateAdGroupCriterionLabelsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupCriterionLabelsRequest;
    AdGroupCriterionLabelOperation: typeof google.ads.googleads.v14.services.AdGroupCriterionLabelOperation;
    MutateAdGroupCriterionLabelsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupCriterionLabelsResponse;
    MutateAdGroupCriterionLabelResult: typeof google.ads.googleads.v14.services.MutateAdGroupCriterionLabelResult;
    AdGroupCriterionService: typeof google.ads.googleads.v14.services.AdGroupCriterionService;
    MutateAdGroupCriteriaRequest: typeof google.ads.googleads.v14.services.MutateAdGroupCriteriaRequest;
    AdGroupCriterionOperation: typeof google.ads.googleads.v14.services.AdGroupCriterionOperation;
    MutateAdGroupCriteriaResponse: typeof google.ads.googleads.v14.services.MutateAdGroupCriteriaResponse;
    MutateAdGroupCriterionResult: typeof google.ads.googleads.v14.services.MutateAdGroupCriterionResult;
    AdGroupCustomizerService: typeof google.ads.googleads.v14.services.AdGroupCustomizerService;
    MutateAdGroupCustomizersRequest: typeof google.ads.googleads.v14.services.MutateAdGroupCustomizersRequest;
    AdGroupCustomizerOperation: typeof google.ads.googleads.v14.services.AdGroupCustomizerOperation;
    MutateAdGroupCustomizersResponse: typeof google.ads.googleads.v14.services.MutateAdGroupCustomizersResponse;
    MutateAdGroupCustomizerResult: typeof google.ads.googleads.v14.services.MutateAdGroupCustomizerResult;
    AdGroupExtensionSettingService: typeof google.ads.googleads.v14.services.AdGroupExtensionSettingService;
    MutateAdGroupExtensionSettingsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupExtensionSettingsRequest;
    AdGroupExtensionSettingOperation: typeof google.ads.googleads.v14.services.AdGroupExtensionSettingOperation;
    MutateAdGroupExtensionSettingsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupExtensionSettingsResponse;
    MutateAdGroupExtensionSettingResult: typeof google.ads.googleads.v14.services.MutateAdGroupExtensionSettingResult;
    AdGroupFeedService: typeof google.ads.googleads.v14.services.AdGroupFeedService;
    MutateAdGroupFeedsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupFeedsRequest;
    AdGroupFeedOperation: typeof google.ads.googleads.v14.services.AdGroupFeedOperation;
    MutateAdGroupFeedsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupFeedsResponse;
    MutateAdGroupFeedResult: typeof google.ads.googleads.v14.services.MutateAdGroupFeedResult;
    AdGroupLabelService: typeof google.ads.googleads.v14.services.AdGroupLabelService;
    MutateAdGroupLabelsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupLabelsRequest;
    AdGroupLabelOperation: typeof google.ads.googleads.v14.services.AdGroupLabelOperation;
    MutateAdGroupLabelsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupLabelsResponse;
    MutateAdGroupLabelResult: typeof google.ads.googleads.v14.services.MutateAdGroupLabelResult;
    AdGroupService: typeof google.ads.googleads.v14.services.AdGroupService;
    MutateAdGroupsRequest: typeof google.ads.googleads.v14.services.MutateAdGroupsRequest;
    AdGroupOperation: typeof google.ads.googleads.v14.services.AdGroupOperation;
    MutateAdGroupsResponse: typeof google.ads.googleads.v14.services.MutateAdGroupsResponse;
    MutateAdGroupResult: typeof google.ads.googleads.v14.services.MutateAdGroupResult;
    AdParameterService: typeof google.ads.googleads.v14.services.AdParameterService;
    MutateAdParametersRequest: typeof google.ads.googleads.v14.services.MutateAdParametersRequest;
    AdParameterOperation: typeof google.ads.googleads.v14.services.AdParameterOperation;
    MutateAdParametersResponse: typeof google.ads.googleads.v14.services.MutateAdParametersResponse;
    MutateAdParameterResult: typeof google.ads.googleads.v14.services.MutateAdParameterResult;
    AdService: typeof google.ads.googleads.v14.services.AdService;
    GetAdRequest: typeof google.ads.googleads.v14.services.GetAdRequest;
    MutateAdsRequest: typeof google.ads.googleads.v14.services.MutateAdsRequest;
    AdOperation: typeof google.ads.googleads.v14.services.AdOperation;
    MutateAdsResponse: typeof google.ads.googleads.v14.services.MutateAdsResponse;
    MutateAdResult: typeof google.ads.googleads.v14.services.MutateAdResult;
    AssetGroupAssetService: typeof google.ads.googleads.v14.services.AssetGroupAssetService;
    MutateAssetGroupAssetsRequest: typeof google.ads.googleads.v14.services.MutateAssetGroupAssetsRequest;
    AssetGroupAssetOperation: typeof google.ads.googleads.v14.services.AssetGroupAssetOperation;
    MutateAssetGroupAssetsResponse: typeof google.ads.googleads.v14.services.MutateAssetGroupAssetsResponse;
    MutateAssetGroupAssetResult: typeof google.ads.googleads.v14.services.MutateAssetGroupAssetResult;
    AssetGroupListingGroupFilterService: typeof google.ads.googleads.v14.services.AssetGroupListingGroupFilterService;
    MutateAssetGroupListingGroupFiltersRequest: typeof google.ads.googleads.v14.services.MutateAssetGroupListingGroupFiltersRequest;
    AssetGroupListingGroupFilterOperation: typeof google.ads.googleads.v14.services.AssetGroupListingGroupFilterOperation;
    MutateAssetGroupListingGroupFiltersResponse: typeof google.ads.googleads.v14.services.MutateAssetGroupListingGroupFiltersResponse;
    MutateAssetGroupListingGroupFilterResult: typeof google.ads.googleads.v14.services.MutateAssetGroupListingGroupFilterResult;
    AssetGroupService: typeof google.ads.googleads.v14.services.AssetGroupService;
    MutateAssetGroupsRequest: typeof google.ads.googleads.v14.services.MutateAssetGroupsRequest;
    AssetGroupOperation: typeof google.ads.googleads.v14.services.AssetGroupOperation;
    MutateAssetGroupsResponse: typeof google.ads.googleads.v14.services.MutateAssetGroupsResponse;
    MutateAssetGroupResult: typeof google.ads.googleads.v14.services.MutateAssetGroupResult;
    AssetGroupSignalService: typeof google.ads.googleads.v14.services.AssetGroupSignalService;
    MutateAssetGroupSignalsRequest: typeof google.ads.googleads.v14.services.MutateAssetGroupSignalsRequest;
    AssetGroupSignalOperation: typeof google.ads.googleads.v14.services.AssetGroupSignalOperation;
    MutateAssetGroupSignalsResponse: typeof google.ads.googleads.v14.services.MutateAssetGroupSignalsResponse;
    MutateAssetGroupSignalResult: typeof google.ads.googleads.v14.services.MutateAssetGroupSignalResult;
    AssetService: typeof google.ads.googleads.v14.services.AssetService;
    MutateAssetsRequest: typeof google.ads.googleads.v14.services.MutateAssetsRequest;
    AssetOperation: typeof google.ads.googleads.v14.services.AssetOperation;
    MutateAssetsResponse: typeof google.ads.googleads.v14.services.MutateAssetsResponse;
    MutateAssetResult: typeof google.ads.googleads.v14.services.MutateAssetResult;
    AssetSetAssetService: typeof google.ads.googleads.v14.services.AssetSetAssetService;
    MutateAssetSetAssetsRequest: typeof google.ads.googleads.v14.services.MutateAssetSetAssetsRequest;
    AssetSetAssetOperation: typeof google.ads.googleads.v14.services.AssetSetAssetOperation;
    MutateAssetSetAssetsResponse: typeof google.ads.googleads.v14.services.MutateAssetSetAssetsResponse;
    MutateAssetSetAssetResult: typeof google.ads.googleads.v14.services.MutateAssetSetAssetResult;
    AssetSetService: typeof google.ads.googleads.v14.services.AssetSetService;
    MutateAssetSetsRequest: typeof google.ads.googleads.v14.services.MutateAssetSetsRequest;
    AssetSetOperation: typeof google.ads.googleads.v14.services.AssetSetOperation;
    MutateAssetSetsResponse: typeof google.ads.googleads.v14.services.MutateAssetSetsResponse;
    MutateAssetSetResult: typeof google.ads.googleads.v14.services.MutateAssetSetResult;
    AudienceInsightsService: typeof google.ads.googleads.v14.services.AudienceInsightsService;
    GenerateInsightsFinderReportRequest: typeof google.ads.googleads.v14.services.GenerateInsightsFinderReportRequest;
    GenerateInsightsFinderReportResponse: typeof google.ads.googleads.v14.services.GenerateInsightsFinderReportResponse;
    GenerateAudienceCompositionInsightsRequest: typeof google.ads.googleads.v14.services.GenerateAudienceCompositionInsightsRequest;
    GenerateAudienceCompositionInsightsResponse: typeof google.ads.googleads.v14.services.GenerateAudienceCompositionInsightsResponse;
    ListAudienceInsightsAttributesRequest: typeof google.ads.googleads.v14.services.ListAudienceInsightsAttributesRequest;
    ListAudienceInsightsAttributesResponse: typeof google.ads.googleads.v14.services.ListAudienceInsightsAttributesResponse;
    ListInsightsEligibleDatesRequest: typeof google.ads.googleads.v14.services.ListInsightsEligibleDatesRequest;
    ListInsightsEligibleDatesResponse: typeof google.ads.googleads.v14.services.ListInsightsEligibleDatesResponse;
    AudienceInsightsAttribute: typeof google.ads.googleads.v14.services.AudienceInsightsAttribute;
    AudienceInsightsTopic: typeof google.ads.googleads.v14.services.AudienceInsightsTopic;
    AudienceInsightsEntity: typeof google.ads.googleads.v14.services.AudienceInsightsEntity;
    AudienceInsightsCategory: typeof google.ads.googleads.v14.services.AudienceInsightsCategory;
    AudienceInsightsDynamicLineup: typeof google.ads.googleads.v14.services.AudienceInsightsDynamicLineup;
    BasicInsightsAudience: typeof google.ads.googleads.v14.services.BasicInsightsAudience;
    AudienceInsightsAttributeMetadata: typeof google.ads.googleads.v14.services.AudienceInsightsAttributeMetadata;
    YouTubeChannelAttributeMetadata: typeof google.ads.googleads.v14.services.YouTubeChannelAttributeMetadata;
    DynamicLineupAttributeMetadata: typeof google.ads.googleads.v14.services.DynamicLineupAttributeMetadata;
    LocationAttributeMetadata: typeof google.ads.googleads.v14.services.LocationAttributeMetadata;
    InsightsAudience: typeof google.ads.googleads.v14.services.InsightsAudience;
    InsightsAudienceAttributeGroup: typeof google.ads.googleads.v14.services.InsightsAudienceAttributeGroup;
    AudienceCompositionSection: typeof google.ads.googleads.v14.services.AudienceCompositionSection;
    AudienceCompositionAttributeCluster: typeof google.ads.googleads.v14.services.AudienceCompositionAttributeCluster;
    AudienceCompositionMetrics: typeof google.ads.googleads.v14.services.AudienceCompositionMetrics;
    AudienceCompositionAttribute: typeof google.ads.googleads.v14.services.AudienceCompositionAttribute;
    AudienceService: typeof google.ads.googleads.v14.services.AudienceService;
    MutateAudiencesRequest: typeof google.ads.googleads.v14.services.MutateAudiencesRequest;
    MutateAudiencesResponse: typeof google.ads.googleads.v14.services.MutateAudiencesResponse;
    AudienceOperation: typeof google.ads.googleads.v14.services.AudienceOperation;
    MutateAudienceResult: typeof google.ads.googleads.v14.services.MutateAudienceResult;
    BatchJobService: typeof google.ads.googleads.v14.services.BatchJobService;
    MutateBatchJobRequest: typeof google.ads.googleads.v14.services.MutateBatchJobRequest;
    BatchJobOperation: typeof google.ads.googleads.v14.services.BatchJobOperation;
    MutateBatchJobResponse: typeof google.ads.googleads.v14.services.MutateBatchJobResponse;
    MutateBatchJobResult: typeof google.ads.googleads.v14.services.MutateBatchJobResult;
    RunBatchJobRequest: typeof google.ads.googleads.v14.services.RunBatchJobRequest;
    AddBatchJobOperationsRequest: typeof google.ads.googleads.v14.services.AddBatchJobOperationsRequest;
    AddBatchJobOperationsResponse: typeof google.ads.googleads.v14.services.AddBatchJobOperationsResponse;
    ListBatchJobResultsRequest: typeof google.ads.googleads.v14.services.ListBatchJobResultsRequest;
    ListBatchJobResultsResponse: typeof google.ads.googleads.v14.services.ListBatchJobResultsResponse;
    BatchJobResult: typeof google.ads.googleads.v14.services.BatchJobResult;
    BiddingDataExclusionService: typeof google.ads.googleads.v14.services.BiddingDataExclusionService;
    MutateBiddingDataExclusionsRequest: typeof google.ads.googleads.v14.services.MutateBiddingDataExclusionsRequest;
    BiddingDataExclusionOperation: typeof google.ads.googleads.v14.services.BiddingDataExclusionOperation;
    MutateBiddingDataExclusionsResponse: typeof google.ads.googleads.v14.services.MutateBiddingDataExclusionsResponse;
    MutateBiddingDataExclusionsResult: typeof google.ads.googleads.v14.services.MutateBiddingDataExclusionsResult;
    BiddingSeasonalityAdjustmentService: typeof google.ads.googleads.v14.services.BiddingSeasonalityAdjustmentService;
    MutateBiddingSeasonalityAdjustmentsRequest: typeof google.ads.googleads.v14.services.MutateBiddingSeasonalityAdjustmentsRequest;
    BiddingSeasonalityAdjustmentOperation: typeof google.ads.googleads.v14.services.BiddingSeasonalityAdjustmentOperation;
    MutateBiddingSeasonalityAdjustmentsResponse: typeof google.ads.googleads.v14.services.MutateBiddingSeasonalityAdjustmentsResponse;
    MutateBiddingSeasonalityAdjustmentsResult: typeof google.ads.googleads.v14.services.MutateBiddingSeasonalityAdjustmentsResult;
    BiddingStrategyService: typeof google.ads.googleads.v14.services.BiddingStrategyService;
    MutateBiddingStrategiesRequest: typeof google.ads.googleads.v14.services.MutateBiddingStrategiesRequest;
    BiddingStrategyOperation: typeof google.ads.googleads.v14.services.BiddingStrategyOperation;
    MutateBiddingStrategiesResponse: typeof google.ads.googleads.v14.services.MutateBiddingStrategiesResponse;
    MutateBiddingStrategyResult: typeof google.ads.googleads.v14.services.MutateBiddingStrategyResult;
    BillingSetupService: typeof google.ads.googleads.v14.services.BillingSetupService;
    MutateBillingSetupRequest: typeof google.ads.googleads.v14.services.MutateBillingSetupRequest;
    BillingSetupOperation: typeof google.ads.googleads.v14.services.BillingSetupOperation;
    MutateBillingSetupResponse: typeof google.ads.googleads.v14.services.MutateBillingSetupResponse;
    MutateBillingSetupResult: typeof google.ads.googleads.v14.services.MutateBillingSetupResult;
    CampaignAssetService: typeof google.ads.googleads.v14.services.CampaignAssetService;
    MutateCampaignAssetsRequest: typeof google.ads.googleads.v14.services.MutateCampaignAssetsRequest;
    CampaignAssetOperation: typeof google.ads.googleads.v14.services.CampaignAssetOperation;
    MutateCampaignAssetsResponse: typeof google.ads.googleads.v14.services.MutateCampaignAssetsResponse;
    MutateCampaignAssetResult: typeof google.ads.googleads.v14.services.MutateCampaignAssetResult;
    CampaignAssetSetService: typeof google.ads.googleads.v14.services.CampaignAssetSetService;
    MutateCampaignAssetSetsRequest: typeof google.ads.googleads.v14.services.MutateCampaignAssetSetsRequest;
    CampaignAssetSetOperation: typeof google.ads.googleads.v14.services.CampaignAssetSetOperation;
    MutateCampaignAssetSetsResponse: typeof google.ads.googleads.v14.services.MutateCampaignAssetSetsResponse;
    MutateCampaignAssetSetResult: typeof google.ads.googleads.v14.services.MutateCampaignAssetSetResult;
    CampaignBidModifierService: typeof google.ads.googleads.v14.services.CampaignBidModifierService;
    MutateCampaignBidModifiersRequest: typeof google.ads.googleads.v14.services.MutateCampaignBidModifiersRequest;
    CampaignBidModifierOperation: typeof google.ads.googleads.v14.services.CampaignBidModifierOperation;
    MutateCampaignBidModifiersResponse: typeof google.ads.googleads.v14.services.MutateCampaignBidModifiersResponse;
    MutateCampaignBidModifierResult: typeof google.ads.googleads.v14.services.MutateCampaignBidModifierResult;
    CampaignBudgetService: typeof google.ads.googleads.v14.services.CampaignBudgetService;
    MutateCampaignBudgetsRequest: typeof google.ads.googleads.v14.services.MutateCampaignBudgetsRequest;
    CampaignBudgetOperation: typeof google.ads.googleads.v14.services.CampaignBudgetOperation;
    MutateCampaignBudgetsResponse: typeof google.ads.googleads.v14.services.MutateCampaignBudgetsResponse;
    MutateCampaignBudgetResult: typeof google.ads.googleads.v14.services.MutateCampaignBudgetResult;
    CampaignConversionGoalService: typeof google.ads.googleads.v14.services.CampaignConversionGoalService;
    MutateCampaignConversionGoalsRequest: typeof google.ads.googleads.v14.services.MutateCampaignConversionGoalsRequest;
    CampaignConversionGoalOperation: typeof google.ads.googleads.v14.services.CampaignConversionGoalOperation;
    MutateCampaignConversionGoalsResponse: typeof google.ads.googleads.v14.services.MutateCampaignConversionGoalsResponse;
    MutateCampaignConversionGoalResult: typeof google.ads.googleads.v14.services.MutateCampaignConversionGoalResult;
    CampaignCriterionService: typeof google.ads.googleads.v14.services.CampaignCriterionService;
    MutateCampaignCriteriaRequest: typeof google.ads.googleads.v14.services.MutateCampaignCriteriaRequest;
    CampaignCriterionOperation: typeof google.ads.googleads.v14.services.CampaignCriterionOperation;
    MutateCampaignCriteriaResponse: typeof google.ads.googleads.v14.services.MutateCampaignCriteriaResponse;
    MutateCampaignCriterionResult: typeof google.ads.googleads.v14.services.MutateCampaignCriterionResult;
    CampaignCustomizerService: typeof google.ads.googleads.v14.services.CampaignCustomizerService;
    MutateCampaignCustomizersRequest: typeof google.ads.googleads.v14.services.MutateCampaignCustomizersRequest;
    CampaignCustomizerOperation: typeof google.ads.googleads.v14.services.CampaignCustomizerOperation;
    MutateCampaignCustomizersResponse: typeof google.ads.googleads.v14.services.MutateCampaignCustomizersResponse;
    MutateCampaignCustomizerResult: typeof google.ads.googleads.v14.services.MutateCampaignCustomizerResult;
    CampaignDraftService: typeof google.ads.googleads.v14.services.CampaignDraftService;
    MutateCampaignDraftsRequest: typeof google.ads.googleads.v14.services.MutateCampaignDraftsRequest;
    PromoteCampaignDraftRequest: typeof google.ads.googleads.v14.services.PromoteCampaignDraftRequest;
    CampaignDraftOperation: typeof google.ads.googleads.v14.services.CampaignDraftOperation;
    MutateCampaignDraftsResponse: typeof google.ads.googleads.v14.services.MutateCampaignDraftsResponse;
    MutateCampaignDraftResult: typeof google.ads.googleads.v14.services.MutateCampaignDraftResult;
    ListCampaignDraftAsyncErrorsRequest: typeof google.ads.googleads.v14.services.ListCampaignDraftAsyncErrorsRequest;
    ListCampaignDraftAsyncErrorsResponse: typeof google.ads.googleads.v14.services.ListCampaignDraftAsyncErrorsResponse;
    CampaignExtensionSettingService: typeof google.ads.googleads.v14.services.CampaignExtensionSettingService;
    MutateCampaignExtensionSettingsRequest: typeof google.ads.googleads.v14.services.MutateCampaignExtensionSettingsRequest;
    CampaignExtensionSettingOperation: typeof google.ads.googleads.v14.services.CampaignExtensionSettingOperation;
    MutateCampaignExtensionSettingsResponse: typeof google.ads.googleads.v14.services.MutateCampaignExtensionSettingsResponse;
    MutateCampaignExtensionSettingResult: typeof google.ads.googleads.v14.services.MutateCampaignExtensionSettingResult;
    CampaignFeedService: typeof google.ads.googleads.v14.services.CampaignFeedService;
    MutateCampaignFeedsRequest: typeof google.ads.googleads.v14.services.MutateCampaignFeedsRequest;
    CampaignFeedOperation: typeof google.ads.googleads.v14.services.CampaignFeedOperation;
    MutateCampaignFeedsResponse: typeof google.ads.googleads.v14.services.MutateCampaignFeedsResponse;
    MutateCampaignFeedResult: typeof google.ads.googleads.v14.services.MutateCampaignFeedResult;
    CampaignGroupService: typeof google.ads.googleads.v14.services.CampaignGroupService;
    MutateCampaignGroupsRequest: typeof google.ads.googleads.v14.services.MutateCampaignGroupsRequest;
    CampaignGroupOperation: typeof google.ads.googleads.v14.services.CampaignGroupOperation;
    MutateCampaignGroupsResponse: typeof google.ads.googleads.v14.services.MutateCampaignGroupsResponse;
    MutateCampaignGroupResult: typeof google.ads.googleads.v14.services.MutateCampaignGroupResult;
    CampaignLabelService: typeof google.ads.googleads.v14.services.CampaignLabelService;
    MutateCampaignLabelsRequest: typeof google.ads.googleads.v14.services.MutateCampaignLabelsRequest;
    CampaignLabelOperation: typeof google.ads.googleads.v14.services.CampaignLabelOperation;
    MutateCampaignLabelsResponse: typeof google.ads.googleads.v14.services.MutateCampaignLabelsResponse;
    MutateCampaignLabelResult: typeof google.ads.googleads.v14.services.MutateCampaignLabelResult;
    CampaignService: typeof google.ads.googleads.v14.services.CampaignService;
    MutateCampaignsRequest: typeof google.ads.googleads.v14.services.MutateCampaignsRequest;
    CampaignOperation: typeof google.ads.googleads.v14.services.CampaignOperation;
    MutateCampaignsResponse: typeof google.ads.googleads.v14.services.MutateCampaignsResponse;
    MutateCampaignResult: typeof google.ads.googleads.v14.services.MutateCampaignResult;
    CampaignSharedSetService: typeof google.ads.googleads.v14.services.CampaignSharedSetService;
    MutateCampaignSharedSetsRequest: typeof google.ads.googleads.v14.services.MutateCampaignSharedSetsRequest;
    CampaignSharedSetOperation: typeof google.ads.googleads.v14.services.CampaignSharedSetOperation;
    MutateCampaignSharedSetsResponse: typeof google.ads.googleads.v14.services.MutateCampaignSharedSetsResponse;
    MutateCampaignSharedSetResult: typeof google.ads.googleads.v14.services.MutateCampaignSharedSetResult;
    ConversionActionService: typeof google.ads.googleads.v14.services.ConversionActionService;
    MutateConversionActionsRequest: typeof google.ads.googleads.v14.services.MutateConversionActionsRequest;
    ConversionActionOperation: typeof google.ads.googleads.v14.services.ConversionActionOperation;
    MutateConversionActionsResponse: typeof google.ads.googleads.v14.services.MutateConversionActionsResponse;
    MutateConversionActionResult: typeof google.ads.googleads.v14.services.MutateConversionActionResult;
    ConversionAdjustmentUploadService: typeof google.ads.googleads.v14.services.ConversionAdjustmentUploadService;
    UploadConversionAdjustmentsRequest: typeof google.ads.googleads.v14.services.UploadConversionAdjustmentsRequest;
    UploadConversionAdjustmentsResponse: typeof google.ads.googleads.v14.services.UploadConversionAdjustmentsResponse;
    ConversionAdjustment: typeof google.ads.googleads.v14.services.ConversionAdjustment;
    RestatementValue: typeof google.ads.googleads.v14.services.RestatementValue;
    GclidDateTimePair: typeof google.ads.googleads.v14.services.GclidDateTimePair;
    ConversionAdjustmentResult: typeof google.ads.googleads.v14.services.ConversionAdjustmentResult;
    ConversionCustomVariableService: typeof google.ads.googleads.v14.services.ConversionCustomVariableService;
    MutateConversionCustomVariablesRequest: typeof google.ads.googleads.v14.services.MutateConversionCustomVariablesRequest;
    ConversionCustomVariableOperation: typeof google.ads.googleads.v14.services.ConversionCustomVariableOperation;
    MutateConversionCustomVariablesResponse: typeof google.ads.googleads.v14.services.MutateConversionCustomVariablesResponse;
    MutateConversionCustomVariableResult: typeof google.ads.googleads.v14.services.MutateConversionCustomVariableResult;
    ConversionGoalCampaignConfigService: typeof google.ads.googleads.v14.services.ConversionGoalCampaignConfigService;
    MutateConversionGoalCampaignConfigsRequest: typeof google.ads.googleads.v14.services.MutateConversionGoalCampaignConfigsRequest;
    ConversionGoalCampaignConfigOperation: typeof google.ads.googleads.v14.services.ConversionGoalCampaignConfigOperation;
    MutateConversionGoalCampaignConfigsResponse: typeof google.ads.googleads.v14.services.MutateConversionGoalCampaignConfigsResponse;
    MutateConversionGoalCampaignConfigResult: typeof google.ads.googleads.v14.services.MutateConversionGoalCampaignConfigResult;
    ConversionUploadService: typeof google.ads.googleads.v14.services.ConversionUploadService;
    UploadClickConversionsRequest: typeof google.ads.googleads.v14.services.UploadClickConversionsRequest;
    UploadClickConversionsResponse: typeof google.ads.googleads.v14.services.UploadClickConversionsResponse;
    UploadCallConversionsRequest: typeof google.ads.googleads.v14.services.UploadCallConversionsRequest;
    UploadCallConversionsResponse: typeof google.ads.googleads.v14.services.UploadCallConversionsResponse;
    ClickConversion: typeof google.ads.googleads.v14.services.ClickConversion;
    CallConversion: typeof google.ads.googleads.v14.services.CallConversion;
    ExternalAttributionData: typeof google.ads.googleads.v14.services.ExternalAttributionData;
    ClickConversionResult: typeof google.ads.googleads.v14.services.ClickConversionResult;
    CallConversionResult: typeof google.ads.googleads.v14.services.CallConversionResult;
    CustomVariable: typeof google.ads.googleads.v14.services.CustomVariable;
    CartData: typeof google.ads.googleads.v14.services.CartData;
    ConversionValueRuleService: typeof google.ads.googleads.v14.services.ConversionValueRuleService;
    MutateConversionValueRulesRequest: typeof google.ads.googleads.v14.services.MutateConversionValueRulesRequest;
    ConversionValueRuleOperation: typeof google.ads.googleads.v14.services.ConversionValueRuleOperation;
    MutateConversionValueRulesResponse: typeof google.ads.googleads.v14.services.MutateConversionValueRulesResponse;
    MutateConversionValueRuleResult: typeof google.ads.googleads.v14.services.MutateConversionValueRuleResult;
    ConversionValueRuleSetService: typeof google.ads.googleads.v14.services.ConversionValueRuleSetService;
    MutateConversionValueRuleSetsRequest: typeof google.ads.googleads.v14.services.MutateConversionValueRuleSetsRequest;
    ConversionValueRuleSetOperation: typeof google.ads.googleads.v14.services.ConversionValueRuleSetOperation;
    MutateConversionValueRuleSetsResponse: typeof google.ads.googleads.v14.services.MutateConversionValueRuleSetsResponse;
    MutateConversionValueRuleSetResult: typeof google.ads.googleads.v14.services.MutateConversionValueRuleSetResult;
    CustomAudienceService: typeof google.ads.googleads.v14.services.CustomAudienceService;
    MutateCustomAudiencesRequest: typeof google.ads.googleads.v14.services.MutateCustomAudiencesRequest;
    CustomAudienceOperation: typeof google.ads.googleads.v14.services.CustomAudienceOperation;
    MutateCustomAudiencesResponse: typeof google.ads.googleads.v14.services.MutateCustomAudiencesResponse;
    MutateCustomAudienceResult: typeof google.ads.googleads.v14.services.MutateCustomAudienceResult;
    CustomConversionGoalService: typeof google.ads.googleads.v14.services.CustomConversionGoalService;
    MutateCustomConversionGoalsRequest: typeof google.ads.googleads.v14.services.MutateCustomConversionGoalsRequest;
    CustomConversionGoalOperation: typeof google.ads.googleads.v14.services.CustomConversionGoalOperation;
    MutateCustomConversionGoalsResponse: typeof google.ads.googleads.v14.services.MutateCustomConversionGoalsResponse;
    MutateCustomConversionGoalResult: typeof google.ads.googleads.v14.services.MutateCustomConversionGoalResult;
    CustomInterestService: typeof google.ads.googleads.v14.services.CustomInterestService;
    MutateCustomInterestsRequest: typeof google.ads.googleads.v14.services.MutateCustomInterestsRequest;
    CustomInterestOperation: typeof google.ads.googleads.v14.services.CustomInterestOperation;
    MutateCustomInterestsResponse: typeof google.ads.googleads.v14.services.MutateCustomInterestsResponse;
    MutateCustomInterestResult: typeof google.ads.googleads.v14.services.MutateCustomInterestResult;
    CustomerAssetService: typeof google.ads.googleads.v14.services.CustomerAssetService;
    MutateCustomerAssetsRequest: typeof google.ads.googleads.v14.services.MutateCustomerAssetsRequest;
    CustomerAssetOperation: typeof google.ads.googleads.v14.services.CustomerAssetOperation;
    MutateCustomerAssetsResponse: typeof google.ads.googleads.v14.services.MutateCustomerAssetsResponse;
    MutateCustomerAssetResult: typeof google.ads.googleads.v14.services.MutateCustomerAssetResult;
    CustomerAssetSetService: typeof google.ads.googleads.v14.services.CustomerAssetSetService;
    MutateCustomerAssetSetsRequest: typeof google.ads.googleads.v14.services.MutateCustomerAssetSetsRequest;
    CustomerAssetSetOperation: typeof google.ads.googleads.v14.services.CustomerAssetSetOperation;
    MutateCustomerAssetSetsResponse: typeof google.ads.googleads.v14.services.MutateCustomerAssetSetsResponse;
    MutateCustomerAssetSetResult: typeof google.ads.googleads.v14.services.MutateCustomerAssetSetResult;
    CustomerClientLinkService: typeof google.ads.googleads.v14.services.CustomerClientLinkService;
    MutateCustomerClientLinkRequest: typeof google.ads.googleads.v14.services.MutateCustomerClientLinkRequest;
    CustomerClientLinkOperation: typeof google.ads.googleads.v14.services.CustomerClientLinkOperation;
    MutateCustomerClientLinkResponse: typeof google.ads.googleads.v14.services.MutateCustomerClientLinkResponse;
    MutateCustomerClientLinkResult: typeof google.ads.googleads.v14.services.MutateCustomerClientLinkResult;
    CustomerConversionGoalService: typeof google.ads.googleads.v14.services.CustomerConversionGoalService;
    MutateCustomerConversionGoalsRequest: typeof google.ads.googleads.v14.services.MutateCustomerConversionGoalsRequest;
    CustomerConversionGoalOperation: typeof google.ads.googleads.v14.services.CustomerConversionGoalOperation;
    MutateCustomerConversionGoalsResponse: typeof google.ads.googleads.v14.services.MutateCustomerConversionGoalsResponse;
    MutateCustomerConversionGoalResult: typeof google.ads.googleads.v14.services.MutateCustomerConversionGoalResult;
    CustomerCustomizerService: typeof google.ads.googleads.v14.services.CustomerCustomizerService;
    MutateCustomerCustomizersRequest: typeof google.ads.googleads.v14.services.MutateCustomerCustomizersRequest;
    CustomerCustomizerOperation: typeof google.ads.googleads.v14.services.CustomerCustomizerOperation;
    MutateCustomerCustomizersResponse: typeof google.ads.googleads.v14.services.MutateCustomerCustomizersResponse;
    MutateCustomerCustomizerResult: typeof google.ads.googleads.v14.services.MutateCustomerCustomizerResult;
    CustomerExtensionSettingService: typeof google.ads.googleads.v14.services.CustomerExtensionSettingService;
    MutateCustomerExtensionSettingsRequest: typeof google.ads.googleads.v14.services.MutateCustomerExtensionSettingsRequest;
    CustomerExtensionSettingOperation: typeof google.ads.googleads.v14.services.CustomerExtensionSettingOperation;
    MutateCustomerExtensionSettingsResponse: typeof google.ads.googleads.v14.services.MutateCustomerExtensionSettingsResponse;
    MutateCustomerExtensionSettingResult: typeof google.ads.googleads.v14.services.MutateCustomerExtensionSettingResult;
    CustomerFeedService: typeof google.ads.googleads.v14.services.CustomerFeedService;
    MutateCustomerFeedsRequest: typeof google.ads.googleads.v14.services.MutateCustomerFeedsRequest;
    CustomerFeedOperation: typeof google.ads.googleads.v14.services.CustomerFeedOperation;
    MutateCustomerFeedsResponse: typeof google.ads.googleads.v14.services.MutateCustomerFeedsResponse;
    MutateCustomerFeedResult: typeof google.ads.googleads.v14.services.MutateCustomerFeedResult;
    CustomerLabelService: typeof google.ads.googleads.v14.services.CustomerLabelService;
    MutateCustomerLabelsRequest: typeof google.ads.googleads.v14.services.MutateCustomerLabelsRequest;
    CustomerLabelOperation: typeof google.ads.googleads.v14.services.CustomerLabelOperation;
    MutateCustomerLabelsResponse: typeof google.ads.googleads.v14.services.MutateCustomerLabelsResponse;
    MutateCustomerLabelResult: typeof google.ads.googleads.v14.services.MutateCustomerLabelResult;
    CustomerManagerLinkService: typeof google.ads.googleads.v14.services.CustomerManagerLinkService;
    MutateCustomerManagerLinkRequest: typeof google.ads.googleads.v14.services.MutateCustomerManagerLinkRequest;
    MoveManagerLinkRequest: typeof google.ads.googleads.v14.services.MoveManagerLinkRequest;
    CustomerManagerLinkOperation: typeof google.ads.googleads.v14.services.CustomerManagerLinkOperation;
    MutateCustomerManagerLinkResponse: typeof google.ads.googleads.v14.services.MutateCustomerManagerLinkResponse;
    MoveManagerLinkResponse: typeof google.ads.googleads.v14.services.MoveManagerLinkResponse;
    MutateCustomerManagerLinkResult: typeof google.ads.googleads.v14.services.MutateCustomerManagerLinkResult;
    CustomerNegativeCriterionService: typeof google.ads.googleads.v14.services.CustomerNegativeCriterionService;
    MutateCustomerNegativeCriteriaRequest: typeof google.ads.googleads.v14.services.MutateCustomerNegativeCriteriaRequest;
    CustomerNegativeCriterionOperation: typeof google.ads.googleads.v14.services.CustomerNegativeCriterionOperation;
    MutateCustomerNegativeCriteriaResponse: typeof google.ads.googleads.v14.services.MutateCustomerNegativeCriteriaResponse;
    MutateCustomerNegativeCriteriaResult: typeof google.ads.googleads.v14.services.MutateCustomerNegativeCriteriaResult;
    CustomerService: typeof google.ads.googleads.v14.services.CustomerService;
    MutateCustomerRequest: typeof google.ads.googleads.v14.services.MutateCustomerRequest;
    CreateCustomerClientRequest: typeof google.ads.googleads.v14.services.CreateCustomerClientRequest;
    CustomerOperation: typeof google.ads.googleads.v14.services.CustomerOperation;
    CreateCustomerClientResponse: typeof google.ads.googleads.v14.services.CreateCustomerClientResponse;
    MutateCustomerResponse: typeof google.ads.googleads.v14.services.MutateCustomerResponse;
    MutateCustomerResult: typeof google.ads.googleads.v14.services.MutateCustomerResult;
    ListAccessibleCustomersRequest: typeof google.ads.googleads.v14.services.ListAccessibleCustomersRequest;
    ListAccessibleCustomersResponse: typeof google.ads.googleads.v14.services.ListAccessibleCustomersResponse;
    CustomerSkAdNetworkConversionValueSchemaService: typeof google.ads.googleads.v14.services.CustomerSkAdNetworkConversionValueSchemaService;
    CustomerSkAdNetworkConversionValueSchemaOperation: typeof google.ads.googleads.v14.services.CustomerSkAdNetworkConversionValueSchemaOperation;
    MutateCustomerSkAdNetworkConversionValueSchemaRequest: typeof google.ads.googleads.v14.services.MutateCustomerSkAdNetworkConversionValueSchemaRequest;
    MutateCustomerSkAdNetworkConversionValueSchemaResult: typeof google.ads.googleads.v14.services.MutateCustomerSkAdNetworkConversionValueSchemaResult;
    MutateCustomerSkAdNetworkConversionValueSchemaResponse: typeof google.ads.googleads.v14.services.MutateCustomerSkAdNetworkConversionValueSchemaResponse;
    CustomerUserAccessInvitationService: typeof google.ads.googleads.v14.services.CustomerUserAccessInvitationService;
    MutateCustomerUserAccessInvitationRequest: typeof google.ads.googleads.v14.services.MutateCustomerUserAccessInvitationRequest;
    CustomerUserAccessInvitationOperation: typeof google.ads.googleads.v14.services.CustomerUserAccessInvitationOperation;
    MutateCustomerUserAccessInvitationResponse: typeof google.ads.googleads.v14.services.MutateCustomerUserAccessInvitationResponse;
    MutateCustomerUserAccessInvitationResult: typeof google.ads.googleads.v14.services.MutateCustomerUserAccessInvitationResult;
    CustomerUserAccessService: typeof google.ads.googleads.v14.services.CustomerUserAccessService;
    MutateCustomerUserAccessRequest: typeof google.ads.googleads.v14.services.MutateCustomerUserAccessRequest;
    CustomerUserAccessOperation: typeof google.ads.googleads.v14.services.CustomerUserAccessOperation;
    MutateCustomerUserAccessResponse: typeof google.ads.googleads.v14.services.MutateCustomerUserAccessResponse;
    MutateCustomerUserAccessResult: typeof google.ads.googleads.v14.services.MutateCustomerUserAccessResult;
    CustomizerAttributeService: typeof google.ads.googleads.v14.services.CustomizerAttributeService;
    MutateCustomizerAttributesRequest: typeof google.ads.googleads.v14.services.MutateCustomizerAttributesRequest;
    CustomizerAttributeOperation: typeof google.ads.googleads.v14.services.CustomizerAttributeOperation;
    MutateCustomizerAttributesResponse: typeof google.ads.googleads.v14.services.MutateCustomizerAttributesResponse;
    MutateCustomizerAttributeResult: typeof google.ads.googleads.v14.services.MutateCustomizerAttributeResult;
    ExperimentArmService: typeof google.ads.googleads.v14.services.ExperimentArmService;
    MutateExperimentArmsRequest: typeof google.ads.googleads.v14.services.MutateExperimentArmsRequest;
    ExperimentArmOperation: typeof google.ads.googleads.v14.services.ExperimentArmOperation;
    MutateExperimentArmsResponse: typeof google.ads.googleads.v14.services.MutateExperimentArmsResponse;
    MutateExperimentArmResult: typeof google.ads.googleads.v14.services.MutateExperimentArmResult;
    ExperimentService: typeof google.ads.googleads.v14.services.ExperimentService;
    MutateExperimentsRequest: typeof google.ads.googleads.v14.services.MutateExperimentsRequest;
    ExperimentOperation: typeof google.ads.googleads.v14.services.ExperimentOperation;
    MutateExperimentsResponse: typeof google.ads.googleads.v14.services.MutateExperimentsResponse;
    MutateExperimentResult: typeof google.ads.googleads.v14.services.MutateExperimentResult;
    EndExperimentRequest: typeof google.ads.googleads.v14.services.EndExperimentRequest;
    ListExperimentAsyncErrorsRequest: typeof google.ads.googleads.v14.services.ListExperimentAsyncErrorsRequest;
    ListExperimentAsyncErrorsResponse: typeof google.ads.googleads.v14.services.ListExperimentAsyncErrorsResponse;
    GraduateExperimentRequest: typeof google.ads.googleads.v14.services.GraduateExperimentRequest;
    CampaignBudgetMapping: typeof google.ads.googleads.v14.services.CampaignBudgetMapping;
    ScheduleExperimentRequest: typeof google.ads.googleads.v14.services.ScheduleExperimentRequest;
    ScheduleExperimentMetadata: typeof google.ads.googleads.v14.services.ScheduleExperimentMetadata;
    PromoteExperimentRequest: typeof google.ads.googleads.v14.services.PromoteExperimentRequest;
    PromoteExperimentMetadata: typeof google.ads.googleads.v14.services.PromoteExperimentMetadata;
    ExtensionFeedItemService: typeof google.ads.googleads.v14.services.ExtensionFeedItemService;
    MutateExtensionFeedItemsRequest: typeof google.ads.googleads.v14.services.MutateExtensionFeedItemsRequest;
    ExtensionFeedItemOperation: typeof google.ads.googleads.v14.services.ExtensionFeedItemOperation;
    MutateExtensionFeedItemsResponse: typeof google.ads.googleads.v14.services.MutateExtensionFeedItemsResponse;
    MutateExtensionFeedItemResult: typeof google.ads.googleads.v14.services.MutateExtensionFeedItemResult;
    FeedItemService: typeof google.ads.googleads.v14.services.FeedItemService;
    MutateFeedItemsRequest: typeof google.ads.googleads.v14.services.MutateFeedItemsRequest;
    FeedItemOperation: typeof google.ads.googleads.v14.services.FeedItemOperation;
    MutateFeedItemsResponse: typeof google.ads.googleads.v14.services.MutateFeedItemsResponse;
    MutateFeedItemResult: typeof google.ads.googleads.v14.services.MutateFeedItemResult;
    FeedItemSetLinkService: typeof google.ads.googleads.v14.services.FeedItemSetLinkService;
    MutateFeedItemSetLinksRequest: typeof google.ads.googleads.v14.services.MutateFeedItemSetLinksRequest;
    FeedItemSetLinkOperation: typeof google.ads.googleads.v14.services.FeedItemSetLinkOperation;
    MutateFeedItemSetLinksResponse: typeof google.ads.googleads.v14.services.MutateFeedItemSetLinksResponse;
    MutateFeedItemSetLinkResult: typeof google.ads.googleads.v14.services.MutateFeedItemSetLinkResult;
    FeedItemSetService: typeof google.ads.googleads.v14.services.FeedItemSetService;
    MutateFeedItemSetsRequest: typeof google.ads.googleads.v14.services.MutateFeedItemSetsRequest;
    FeedItemSetOperation: typeof google.ads.googleads.v14.services.FeedItemSetOperation;
    MutateFeedItemSetsResponse: typeof google.ads.googleads.v14.services.MutateFeedItemSetsResponse;
    MutateFeedItemSetResult: typeof google.ads.googleads.v14.services.MutateFeedItemSetResult;
    FeedItemTargetService: typeof google.ads.googleads.v14.services.FeedItemTargetService;
    MutateFeedItemTargetsRequest: typeof google.ads.googleads.v14.services.MutateFeedItemTargetsRequest;
    FeedItemTargetOperation: typeof google.ads.googleads.v14.services.FeedItemTargetOperation;
    MutateFeedItemTargetsResponse: typeof google.ads.googleads.v14.services.MutateFeedItemTargetsResponse;
    MutateFeedItemTargetResult: typeof google.ads.googleads.v14.services.MutateFeedItemTargetResult;
    FeedMappingService: typeof google.ads.googleads.v14.services.FeedMappingService;
    MutateFeedMappingsRequest: typeof google.ads.googleads.v14.services.MutateFeedMappingsRequest;
    FeedMappingOperation: typeof google.ads.googleads.v14.services.FeedMappingOperation;
    MutateFeedMappingsResponse: typeof google.ads.googleads.v14.services.MutateFeedMappingsResponse;
    MutateFeedMappingResult: typeof google.ads.googleads.v14.services.MutateFeedMappingResult;
    FeedService: typeof google.ads.googleads.v14.services.FeedService;
    MutateFeedsRequest: typeof google.ads.googleads.v14.services.MutateFeedsRequest;
    FeedOperation: typeof google.ads.googleads.v14.services.FeedOperation;
    MutateFeedsResponse: typeof google.ads.googleads.v14.services.MutateFeedsResponse;
    MutateFeedResult: typeof google.ads.googleads.v14.services.MutateFeedResult;
    GeoTargetConstantService: typeof google.ads.googleads.v14.services.GeoTargetConstantService;
    SuggestGeoTargetConstantsRequest: typeof google.ads.googleads.v14.services.SuggestGeoTargetConstantsRequest;
    SuggestGeoTargetConstantsResponse: typeof google.ads.googleads.v14.services.SuggestGeoTargetConstantsResponse;
    GeoTargetConstantSuggestion: typeof google.ads.googleads.v14.services.GeoTargetConstantSuggestion;
    GoogleAdsFieldService: typeof google.ads.googleads.v14.services.GoogleAdsFieldService;
    GetGoogleAdsFieldRequest: typeof google.ads.googleads.v14.services.GetGoogleAdsFieldRequest;
    SearchGoogleAdsFieldsRequest: typeof google.ads.googleads.v14.services.SearchGoogleAdsFieldsRequest;
    SearchGoogleAdsFieldsResponse: typeof google.ads.googleads.v14.services.SearchGoogleAdsFieldsResponse;
    GoogleAdsService: typeof google.ads.googleads.v14.services.GoogleAdsService;
    SearchGoogleAdsRequest: typeof google.ads.googleads.v14.services.SearchGoogleAdsRequest;
    SearchGoogleAdsResponse: typeof google.ads.googleads.v14.services.SearchGoogleAdsResponse;
    SearchGoogleAdsStreamRequest: typeof google.ads.googleads.v14.services.SearchGoogleAdsStreamRequest;
    SearchGoogleAdsStreamResponse: typeof google.ads.googleads.v14.services.SearchGoogleAdsStreamResponse;
    GoogleAdsRow: typeof google.ads.googleads.v14.services.GoogleAdsRow;
    MutateGoogleAdsRequest: typeof google.ads.googleads.v14.services.MutateGoogleAdsRequest;
    MutateGoogleAdsResponse: typeof google.ads.googleads.v14.services.MutateGoogleAdsResponse;
    MutateOperation: typeof google.ads.googleads.v14.services.MutateOperation;
    MutateOperationResponse: typeof google.ads.googleads.v14.services.MutateOperationResponse;
    InvoiceService: typeof google.ads.googleads.v14.services.InvoiceService;
    ListInvoicesRequest: typeof google.ads.googleads.v14.services.ListInvoicesRequest;
    ListInvoicesResponse: typeof google.ads.googleads.v14.services.ListInvoicesResponse;
    KeywordPlanAdGroupKeywordService: typeof google.ads.googleads.v14.services.KeywordPlanAdGroupKeywordService;
    MutateKeywordPlanAdGroupKeywordsRequest: typeof google.ads.googleads.v14.services.MutateKeywordPlanAdGroupKeywordsRequest;
    KeywordPlanAdGroupKeywordOperation: typeof google.ads.googleads.v14.services.KeywordPlanAdGroupKeywordOperation;
    MutateKeywordPlanAdGroupKeywordsResponse: typeof google.ads.googleads.v14.services.MutateKeywordPlanAdGroupKeywordsResponse;
    MutateKeywordPlanAdGroupKeywordResult: typeof google.ads.googleads.v14.services.MutateKeywordPlanAdGroupKeywordResult;
    KeywordPlanAdGroupService: typeof google.ads.googleads.v14.services.KeywordPlanAdGroupService;
    MutateKeywordPlanAdGroupsRequest: typeof google.ads.googleads.v14.services.MutateKeywordPlanAdGroupsRequest;
    KeywordPlanAdGroupOperation: typeof google.ads.googleads.v14.services.KeywordPlanAdGroupOperation;
    MutateKeywordPlanAdGroupsResponse: typeof google.ads.googleads.v14.services.MutateKeywordPlanAdGroupsResponse;
    MutateKeywordPlanAdGroupResult: typeof google.ads.googleads.v14.services.MutateKeywordPlanAdGroupResult;
    KeywordPlanCampaignKeywordService: typeof google.ads.googleads.v14.services.KeywordPlanCampaignKeywordService;
    MutateKeywordPlanCampaignKeywordsRequest: typeof google.ads.googleads.v14.services.MutateKeywordPlanCampaignKeywordsRequest;
    KeywordPlanCampaignKeywordOperation: typeof google.ads.googleads.v14.services.KeywordPlanCampaignKeywordOperation;
    MutateKeywordPlanCampaignKeywordsResponse: typeof google.ads.googleads.v14.services.MutateKeywordPlanCampaignKeywordsResponse;
    MutateKeywordPlanCampaignKeywordResult: typeof google.ads.googleads.v14.services.MutateKeywordPlanCampaignKeywordResult;
    KeywordPlanCampaignService: typeof google.ads.googleads.v14.services.KeywordPlanCampaignService;
    MutateKeywordPlanCampaignsRequest: typeof google.ads.googleads.v14.services.MutateKeywordPlanCampaignsRequest;
    KeywordPlanCampaignOperation: typeof google.ads.googleads.v14.services.KeywordPlanCampaignOperation;
    MutateKeywordPlanCampaignsResponse: typeof google.ads.googleads.v14.services.MutateKeywordPlanCampaignsResponse;
    MutateKeywordPlanCampaignResult: typeof google.ads.googleads.v14.services.MutateKeywordPlanCampaignResult;
    KeywordPlanIdeaService: typeof google.ads.googleads.v14.services.KeywordPlanIdeaService;
    GenerateKeywordIdeasRequest: typeof google.ads.googleads.v14.services.GenerateKeywordIdeasRequest;
    KeywordAndUrlSeed: typeof google.ads.googleads.v14.services.KeywordAndUrlSeed;
    KeywordSeed: typeof google.ads.googleads.v14.services.KeywordSeed;
    SiteSeed: typeof google.ads.googleads.v14.services.SiteSeed;
    UrlSeed: typeof google.ads.googleads.v14.services.UrlSeed;
    GenerateKeywordIdeaResponse: typeof google.ads.googleads.v14.services.GenerateKeywordIdeaResponse;
    GenerateKeywordIdeaResult: typeof google.ads.googleads.v14.services.GenerateKeywordIdeaResult;
    GenerateKeywordHistoricalMetricsRequest: typeof google.ads.googleads.v14.services.GenerateKeywordHistoricalMetricsRequest;
    GenerateKeywordHistoricalMetricsResponse: typeof google.ads.googleads.v14.services.GenerateKeywordHistoricalMetricsResponse;
    GenerateKeywordHistoricalMetricsResult: typeof google.ads.googleads.v14.services.GenerateKeywordHistoricalMetricsResult;
    GenerateAdGroupThemesRequest: typeof google.ads.googleads.v14.services.GenerateAdGroupThemesRequest;
    GenerateAdGroupThemesResponse: typeof google.ads.googleads.v14.services.GenerateAdGroupThemesResponse;
    AdGroupKeywordSuggestion: typeof google.ads.googleads.v14.services.AdGroupKeywordSuggestion;
    UnusableAdGroup: typeof google.ads.googleads.v14.services.UnusableAdGroup;
    GenerateKeywordForecastMetricsRequest: typeof google.ads.googleads.v14.services.GenerateKeywordForecastMetricsRequest;
    CampaignToForecast: typeof google.ads.googleads.v14.services.CampaignToForecast;
    ForecastAdGroup: typeof google.ads.googleads.v14.services.ForecastAdGroup;
    BiddableKeyword: typeof google.ads.googleads.v14.services.BiddableKeyword;
    CriterionBidModifier: typeof google.ads.googleads.v14.services.CriterionBidModifier;
    ManualCpcBiddingStrategy: typeof google.ads.googleads.v14.services.ManualCpcBiddingStrategy;
    MaximizeClicksBiddingStrategy: typeof google.ads.googleads.v14.services.MaximizeClicksBiddingStrategy;
    MaximizeConversionsBiddingStrategy: typeof google.ads.googleads.v14.services.MaximizeConversionsBiddingStrategy;
    GenerateKeywordForecastMetricsResponse: typeof google.ads.googleads.v14.services.GenerateKeywordForecastMetricsResponse;
    KeywordForecastMetrics: typeof google.ads.googleads.v14.services.KeywordForecastMetrics;
    KeywordPlanService: typeof google.ads.googleads.v14.services.KeywordPlanService;
    MutateKeywordPlansRequest: typeof google.ads.googleads.v14.services.MutateKeywordPlansRequest;
    KeywordPlanOperation: typeof google.ads.googleads.v14.services.KeywordPlanOperation;
    MutateKeywordPlansResponse: typeof google.ads.googleads.v14.services.MutateKeywordPlansResponse;
    MutateKeywordPlansResult: typeof google.ads.googleads.v14.services.MutateKeywordPlansResult;
    KeywordThemeConstantService: typeof google.ads.googleads.v14.services.KeywordThemeConstantService;
    SuggestKeywordThemeConstantsRequest: typeof google.ads.googleads.v14.services.SuggestKeywordThemeConstantsRequest;
    SuggestKeywordThemeConstantsResponse: typeof google.ads.googleads.v14.services.SuggestKeywordThemeConstantsResponse;
    LabelService: typeof google.ads.googleads.v14.services.LabelService;
    MutateLabelsRequest: typeof google.ads.googleads.v14.services.MutateLabelsRequest;
    LabelOperation: typeof google.ads.googleads.v14.services.LabelOperation;
    MutateLabelsResponse: typeof google.ads.googleads.v14.services.MutateLabelsResponse;
    MutateLabelResult: typeof google.ads.googleads.v14.services.MutateLabelResult;
    MediaFileService: typeof google.ads.googleads.v14.services.MediaFileService;
    MutateMediaFilesRequest: typeof google.ads.googleads.v14.services.MutateMediaFilesRequest;
    MediaFileOperation: typeof google.ads.googleads.v14.services.MediaFileOperation;
    MutateMediaFilesResponse: typeof google.ads.googleads.v14.services.MutateMediaFilesResponse;
    MutateMediaFileResult: typeof google.ads.googleads.v14.services.MutateMediaFileResult;
    MerchantCenterLinkService: typeof google.ads.googleads.v14.services.MerchantCenterLinkService;
    ListMerchantCenterLinksRequest: typeof google.ads.googleads.v14.services.ListMerchantCenterLinksRequest;
    ListMerchantCenterLinksResponse: typeof google.ads.googleads.v14.services.ListMerchantCenterLinksResponse;
    GetMerchantCenterLinkRequest: typeof google.ads.googleads.v14.services.GetMerchantCenterLinkRequest;
    MutateMerchantCenterLinkRequest: typeof google.ads.googleads.v14.services.MutateMerchantCenterLinkRequest;
    MerchantCenterLinkOperation: typeof google.ads.googleads.v14.services.MerchantCenterLinkOperation;
    MutateMerchantCenterLinkResponse: typeof google.ads.googleads.v14.services.MutateMerchantCenterLinkResponse;
    MutateMerchantCenterLinkResult: typeof google.ads.googleads.v14.services.MutateMerchantCenterLinkResult;
    OfflineUserDataJobService: typeof google.ads.googleads.v14.services.OfflineUserDataJobService;
    CreateOfflineUserDataJobRequest: typeof google.ads.googleads.v14.services.CreateOfflineUserDataJobRequest;
    CreateOfflineUserDataJobResponse: typeof google.ads.googleads.v14.services.CreateOfflineUserDataJobResponse;
    RunOfflineUserDataJobRequest: typeof google.ads.googleads.v14.services.RunOfflineUserDataJobRequest;
    AddOfflineUserDataJobOperationsRequest: typeof google.ads.googleads.v14.services.AddOfflineUserDataJobOperationsRequest;
    OfflineUserDataJobOperation: typeof google.ads.googleads.v14.services.OfflineUserDataJobOperation;
    AddOfflineUserDataJobOperationsResponse: typeof google.ads.googleads.v14.services.AddOfflineUserDataJobOperationsResponse;
    PaymentsAccountService: typeof google.ads.googleads.v14.services.PaymentsAccountService;
    ListPaymentsAccountsRequest: typeof google.ads.googleads.v14.services.ListPaymentsAccountsRequest;
    ListPaymentsAccountsResponse: typeof google.ads.googleads.v14.services.ListPaymentsAccountsResponse;
    ProductLinkService: typeof google.ads.googleads.v14.services.ProductLinkService;
    CreateProductLinkRequest: typeof google.ads.googleads.v14.services.CreateProductLinkRequest;
    CreateProductLinkResponse: typeof google.ads.googleads.v14.services.CreateProductLinkResponse;
    RemoveProductLinkRequest: typeof google.ads.googleads.v14.services.RemoveProductLinkRequest;
    RemoveProductLinkResponse: typeof google.ads.googleads.v14.services.RemoveProductLinkResponse;
    ReachPlanService: typeof google.ads.googleads.v14.services.ReachPlanService;
    ListPlannableLocationsRequest: typeof google.ads.googleads.v14.services.ListPlannableLocationsRequest;
    ListPlannableLocationsResponse: typeof google.ads.googleads.v14.services.ListPlannableLocationsResponse;
    PlannableLocation: typeof google.ads.googleads.v14.services.PlannableLocation;
    ListPlannableProductsRequest: typeof google.ads.googleads.v14.services.ListPlannableProductsRequest;
    ListPlannableProductsResponse: typeof google.ads.googleads.v14.services.ListPlannableProductsResponse;
    ProductMetadata: typeof google.ads.googleads.v14.services.ProductMetadata;
    PlannableTargeting: typeof google.ads.googleads.v14.services.PlannableTargeting;
    GenerateReachForecastRequest: typeof google.ads.googleads.v14.services.GenerateReachForecastRequest;
    EffectiveFrequencyLimit: typeof google.ads.googleads.v14.services.EffectiveFrequencyLimit;
    FrequencyCap: typeof google.ads.googleads.v14.services.FrequencyCap;
    Targeting: typeof google.ads.googleads.v14.services.Targeting;
    CampaignDuration: typeof google.ads.googleads.v14.services.CampaignDuration;
    PlannedProduct: typeof google.ads.googleads.v14.services.PlannedProduct;
    GenerateReachForecastResponse: typeof google.ads.googleads.v14.services.GenerateReachForecastResponse;
    ReachCurve: typeof google.ads.googleads.v14.services.ReachCurve;
    ReachForecast: typeof google.ads.googleads.v14.services.ReachForecast;
    Forecast: typeof google.ads.googleads.v14.services.Forecast;
    PlannedProductReachForecast: typeof google.ads.googleads.v14.services.PlannedProductReachForecast;
    PlannedProductForecast: typeof google.ads.googleads.v14.services.PlannedProductForecast;
    OnTargetAudienceMetrics: typeof google.ads.googleads.v14.services.OnTargetAudienceMetrics;
    EffectiveFrequencyBreakdown: typeof google.ads.googleads.v14.services.EffectiveFrequencyBreakdown;
    ForecastMetricOptions: typeof google.ads.googleads.v14.services.ForecastMetricOptions;
    AudienceTargeting: typeof google.ads.googleads.v14.services.AudienceTargeting;
    AdvancedProductTargeting: typeof google.ads.googleads.v14.services.AdvancedProductTargeting;
    YouTubeSelectSettings: typeof google.ads.googleads.v14.services.YouTubeSelectSettings;
    YouTubeSelectLineUp: typeof google.ads.googleads.v14.services.YouTubeSelectLineUp;
    RecommendationService: typeof google.ads.googleads.v14.services.RecommendationService;
    ApplyRecommendationRequest: typeof google.ads.googleads.v14.services.ApplyRecommendationRequest;
    ApplyRecommendationOperation: typeof google.ads.googleads.v14.services.ApplyRecommendationOperation;
    ApplyRecommendationResponse: typeof google.ads.googleads.v14.services.ApplyRecommendationResponse;
    ApplyRecommendationResult: typeof google.ads.googleads.v14.services.ApplyRecommendationResult;
    DismissRecommendationRequest: typeof google.ads.googleads.v14.services.DismissRecommendationRequest;
    DismissRecommendationResponse: typeof google.ads.googleads.v14.services.DismissRecommendationResponse;
    RemarketingActionService: typeof google.ads.googleads.v14.services.RemarketingActionService;
    MutateRemarketingActionsRequest: typeof google.ads.googleads.v14.services.MutateRemarketingActionsRequest;
    RemarketingActionOperation: typeof google.ads.googleads.v14.services.RemarketingActionOperation;
    MutateRemarketingActionsResponse: typeof google.ads.googleads.v14.services.MutateRemarketingActionsResponse;
    MutateRemarketingActionResult: typeof google.ads.googleads.v14.services.MutateRemarketingActionResult;
    SharedCriterionService: typeof google.ads.googleads.v14.services.SharedCriterionService;
    MutateSharedCriteriaRequest: typeof google.ads.googleads.v14.services.MutateSharedCriteriaRequest;
    SharedCriterionOperation: typeof google.ads.googleads.v14.services.SharedCriterionOperation;
    MutateSharedCriteriaResponse: typeof google.ads.googleads.v14.services.MutateSharedCriteriaResponse;
    MutateSharedCriterionResult: typeof google.ads.googleads.v14.services.MutateSharedCriterionResult;
    SharedSetService: typeof google.ads.googleads.v14.services.SharedSetService;
    MutateSharedSetsRequest: typeof google.ads.googleads.v14.services.MutateSharedSetsRequest;
    SharedSetOperation: typeof google.ads.googleads.v14.services.SharedSetOperation;
    MutateSharedSetsResponse: typeof google.ads.googleads.v14.services.MutateSharedSetsResponse;
    MutateSharedSetResult: typeof google.ads.googleads.v14.services.MutateSharedSetResult;
    SmartCampaignSettingService: typeof google.ads.googleads.v14.services.SmartCampaignSettingService;
    GetSmartCampaignStatusRequest: typeof google.ads.googleads.v14.services.GetSmartCampaignStatusRequest;
    SmartCampaignNotEligibleDetails: typeof google.ads.googleads.v14.services.SmartCampaignNotEligibleDetails;
    SmartCampaignEligibleDetails: typeof google.ads.googleads.v14.services.SmartCampaignEligibleDetails;
    SmartCampaignPausedDetails: typeof google.ads.googleads.v14.services.SmartCampaignPausedDetails;
    SmartCampaignRemovedDetails: typeof google.ads.googleads.v14.services.SmartCampaignRemovedDetails;
    SmartCampaignEndedDetails: typeof google.ads.googleads.v14.services.SmartCampaignEndedDetails;
    GetSmartCampaignStatusResponse: typeof google.ads.googleads.v14.services.GetSmartCampaignStatusResponse;
    MutateSmartCampaignSettingsRequest: typeof google.ads.googleads.v14.services.MutateSmartCampaignSettingsRequest;
    SmartCampaignSettingOperation: typeof google.ads.googleads.v14.services.SmartCampaignSettingOperation;
    MutateSmartCampaignSettingsResponse: typeof google.ads.googleads.v14.services.MutateSmartCampaignSettingsResponse;
    MutateSmartCampaignSettingResult: typeof google.ads.googleads.v14.services.MutateSmartCampaignSettingResult;
    SmartCampaignSuggestService: typeof google.ads.googleads.v14.services.SmartCampaignSuggestService;
    SuggestSmartCampaignBudgetOptionsRequest: typeof google.ads.googleads.v14.services.SuggestSmartCampaignBudgetOptionsRequest;
    SmartCampaignSuggestionInfo: typeof google.ads.googleads.v14.services.SmartCampaignSuggestionInfo;
    SuggestSmartCampaignBudgetOptionsResponse: typeof google.ads.googleads.v14.services.SuggestSmartCampaignBudgetOptionsResponse;
    SuggestSmartCampaignAdRequest: typeof google.ads.googleads.v14.services.SuggestSmartCampaignAdRequest;
    SuggestSmartCampaignAdResponse: typeof google.ads.googleads.v14.services.SuggestSmartCampaignAdResponse;
    SuggestKeywordThemesRequest: typeof google.ads.googleads.v14.services.SuggestKeywordThemesRequest;
    SuggestKeywordThemesResponse: typeof google.ads.googleads.v14.services.SuggestKeywordThemesResponse;
    ThirdPartyAppAnalyticsLinkService: typeof google.ads.googleads.v14.services.ThirdPartyAppAnalyticsLinkService;
    RegenerateShareableLinkIdRequest: typeof google.ads.googleads.v14.services.RegenerateShareableLinkIdRequest;
    RegenerateShareableLinkIdResponse: typeof google.ads.googleads.v14.services.RegenerateShareableLinkIdResponse;
    TravelAssetSuggestionService: typeof google.ads.googleads.v14.services.TravelAssetSuggestionService;
    SuggestTravelAssetsRequest: typeof google.ads.googleads.v14.services.SuggestTravelAssetsRequest;
    SuggestTravelAssetsResponse: typeof google.ads.googleads.v14.services.SuggestTravelAssetsResponse;
    HotelAssetSuggestion: typeof google.ads.googleads.v14.services.HotelAssetSuggestion;
    HotelTextAsset: typeof google.ads.googleads.v14.services.HotelTextAsset;
    HotelImageAsset: typeof google.ads.googleads.v14.services.HotelImageAsset;
    UserDataService: typeof google.ads.googleads.v14.services.UserDataService;
    UploadUserDataRequest: typeof google.ads.googleads.v14.services.UploadUserDataRequest;
    UserDataOperation: typeof google.ads.googleads.v14.services.UserDataOperation;
    UploadUserDataResponse: typeof google.ads.googleads.v14.services.UploadUserDataResponse;
    UserListService: typeof google.ads.googleads.v14.services.UserListService;
    MutateUserListsRequest: typeof google.ads.googleads.v14.services.MutateUserListsRequest;
    UserListOperation: typeof google.ads.googleads.v14.services.UserListOperation;
    MutateUserListsResponse: typeof google.ads.googleads.v14.services.MutateUserListsResponse;
    MutateUserListResult: typeof google.ads.googleads.v14.services.MutateUserListResult;
};
export type Services = typeof services;
export type ServiceNames = keyof Services;
declare const resources: typeof google.ads.googleads.v14.resources;
export type Resources = typeof resources;
export type ResourceNames = keyof Resources;
export interface Stoppable {
    stop(): void;
}
export interface IServiceCache {
    set<T extends ServiceNames>(serviceName: T, service: InstanceType<Services[T]>): void;
    get<T extends ServiceNames>(serviceName: T): InstanceType<Services[T]> | undefined;
    clear(): void;
}
export declare const createServiceCache: () => IServiceCache;
export interface GoogleAdsClientOptions {
    authOptions: JWTOptions;
    developerToken: string;
    mccAccountId: string;
    timeout?: number;
    clientPoolSize?: number;
    serviceCache?: IServiceCache;
    logger?: Logger;
    statter?: Statter;
}
export declare class ResourceNotFoundError extends Error {
}
export declare class InvalidRPCServiceError extends Error {
}
export interface ClientSearchParams<R extends ResourceNames> {
    customerId: string;
    resource: R;
    filters?: {
        [attr in keyof InstanceType<Resources[R]>]?: boolean | string | number | string[] | number[] | {
            raw: string;
        };
    };
    fields?: string[];
    orderBy?: keyof InstanceType<Resources[R]>;
    orderByDirection?: "ASC" | "DESC";
    limit?: number;
    includeDrafts?: boolean;
}
export interface IGoogleAdsClient extends Stoppable {
    getMccAccountId(): string;
    search<R extends ResourceNames>(params: ClientSearchParams<R>): Promise<Array<InstanceType<Resources[R]>>>;
    findOne<R extends ResourceNames>(customerId: string, resource: R, resourceId: number, fields?: string[]): Promise<InstanceType<Resources[R]>>;
    getService<T extends ServiceNames>(serviceName: T): InstanceType<Services[T]>;
}
export interface ClientCreator {
    (channelCredentials: grpc.ChannelCredentials, callCredentials: grpc.CallCredentials, serviceConfig: string): ServiceClient;
}
/**
 * A very simple round-robin pool for gRPC clients. This is needed for meta since we run
 * a very large number of concurrent requests which try and multiplex over a single Channel
 * that gets overwhelmed and hangs. This provides a dumb mechanism to spread that load
 * across a pool of clients, who each manage a single Channel per scheme/host/port.
 */
export declare class ClientPool {
    private readonly size;
    private readonly pool;
    private currentIndex;
    constructor(authOptions: JWTOptions, size?: number, clientCreator?: ClientCreator);
    getClient(): ServiceClient;
}
export declare class GoogleAdsClient implements IGoogleAdsClient {
    private readonly options;
    private readonly serviceCache;
    private longRunningOps;
    private readonly metadata;
    private readonly clientPool;
    private readonly statter;
    constructor(options: GoogleAdsClientOptions);
    getMccAccountId(): string;
    private getRpcImpl;
    private fieldsCache;
    private getFieldsForTable;
    private buildSearchSql;
    search<R extends ResourceNames>(params: ClientSearchParams<R>): Promise<Array<InstanceType<Resources[R]>>>;
    searchGenerator<R extends ResourceNames>(params: ClientSearchParams<R>): AsyncIterable<InstanceType<Resources[R]>>;
    stop(): void;
    findOne<R extends ResourceNames>(customerId: string, resource: R, resourceId: number, fields?: string[], includeDrafts?: boolean): Promise<InstanceType<Resources[R]>>;
    getService<T extends ServiceNames>(serviceName: T): InstanceType<Services[T]>;
    getLongRunningOperationsService(): google.longrunning.Operations;
}
export declare class GaClientError extends Error implements StatusObject {
    firstError: google.ads.googleads.v14.errors.IErrorCode | null | undefined;
    code: Status;
    details: string;
    metadata: grpc.Metadata;
    constructor(status: grpc.ServiceError);
}
export {};
